name: File yml in Github Actions

on:
  push:
    branches:
      - dev
    paths:
      - .github/workflows/lks-dev-pipeline.yaml
      - gatus/**
      - leantime/**

env:
  AWS_REGION: "us-east-1"
  ECR_REPOSITORY: "lks-gatus"
  ECS_CLUSTER: "lks-oss-cluster-dev"
  LEANTIME_TASK_DEFINITION: leantime/task-definition.json
  ECS_LEANTIME_SERVICE: "leantime-service"

  GATUS_CONFIG_FILE: "gatus/config/config.yaml"
  ECS_GATUS_SERVICE: "gatus-service"
  GATUS_TASK_DEFINITION: "gatus/task-definition.json"
  LEANTIME_URL: ${{ secrets.ALB_ENDPOINT }}

permissions:
  contents: read

jobs:
  deploy-leantime:
    name: Deploy Leantime App
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      # - name: Generate .env file
      #   run: |
      #     echo "LEAN_DB_USER=${{ secrets.LEAN_DB_USER }}" >> .env
      #     echo "LEAN_DB_PASSWORD=${{ secrets.LEAN_DB_PASSWORD }}" >> .env
      #     echo "LEAN_PORT=${{ secrets.LEAN_PORT }}" >> .env

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ env.LEANTIME_TASK_DEFINITION }}
          service: ${{ env.ECS_LEANTIME_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          force-new-deployment: true

  deploy-gatus:
    name: Deploy Gatus App
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Update Gatus config
        env:
          TOKEN: ${{ secrets.TOKEN }}
          GATUS_URL: ${{ secrets.ALB_ENDPOINT }}
          LEANTIME_URL: ${{ secrets.LEANTIME_URL }}
        run: |
          sed -i "s|<github-token>|$TOKEN|g" gatus/config/config.yaml
          sed -i "s|<leantime-url>|$LEANTIME_URL|g" gatus/config/config.yaml
          sed -i "s|<gatus-url>|$GATUS_URL|g" gatus/config/config.yaml
          echo "Cofiguration updated."
          cat gatus/config/config.yaml

      - name: Get Short Commit Hash
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        shell: bash

      - name: Build, tag, and push Docker image to ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          IMAGE_TAG=${{ github.sha }}
          IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker build -t $IMAGE_URI -f gatus/Dockerfile gatus
          docker tag $IMAGE_URI $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $IMAGE_URI
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "IMAGE_FULL_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Update ECS task definition with image URI
        run: |
          sed -i "s|<task-def-image>|$IMAGE_FULL_URI|g" $GATUS_TASK_DEFINITION
          echo "Task definition updated."
          cat $GATUS_TASK_DEFINITION

      - name: Deploy ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ env.GATUS_TASK_DEFINITION }}
          service: ${{ env.ECS_GATUS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          force-new-deployment: true

      - name:  Check if Leantime is Live
        run: |
          echo "Checking if Leantime is live at $LEANTIME_URL ..."
          curl -sSf $LEANTIME_URL || echo "⚠️ Warning: Leantime did not respond"